=== cul-it/cular-metadata/manifest_schema_storage.json
{
    "$id": "https://github.com/cul-it/cular-metadata/blob/main/manifest_schema_storage.json",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "type": "object",
    "properties": {
        "collection_id": {
            "type": "string"
        },
        "depositor": {
            "type": "string"
        },
        "steward": {
            "type": "string",
            "pattern": "^[a-zA-Z]{1,4}[0-9]{1,6}$"
        },
        "documentation": {
            "type": "string",
            "minLength": 2
        },
        "packages": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/package"
            }
        },
        "number_packages": {
            "type": "integer"
        }
    },
    "required": [
        "collection_id",
        "depositor",
        "documentation",
        "packages",
        "number_packages"
    ],
    "additionalProperties": false,
    "definitions": {
        "package": {
            "type": "object",
            "properties": {
                "package_id": {
                    "type": "string",
                    "pattern": "^urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                },
                "bibid": {
                    "type": "string"
                },
                "local_id": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/file"
                    }
                },
                "number_files": {
                    "type": "integer"
                }
            },
            "required": [
                "package_id",
                "files",
                "number_files"
            ],
            "additionalProperties": false
        },
        "file": {
            "type": "object",
            "properties": {
                "filepath": {
                    "type": "string"
                },
                "sha1": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{40}$"
                },
                "md5": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{32}$"
                },
                "size": {
                    "type": "integer"
                },
                "ingest_date": {
                    "type": "string",
                    "pattern": "^[0-9-]{10}$"
                },
                "tool_version": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                }
            },
            "required": [
                "filepath",
                "sha1",
                "size",
                "ingest_date",
                "tool_version",
                "media_type"
            ],
            "additionalProperties": false
        }
    }
}

=== cul-it/cular-metadata/manifest_storage.json
{
  "collection_id": "EXAMPLE_COLLECTION_1",
  "depositor": "DEPOSITOR",
  "steward": "net272",
  "documentation": "urn:uuid:a036a6c0-3038-4bee-a6b6-b80c7a7858ff",
  "number_packages": 1,
  "packages": [
    {
      "package_id": "urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
      "bibid": "123456",
      "local_id": "31924",
      "number_files": 2,
      "files": [
        {
          "filepath": "a_file",
          "sha1": "058bbd836dfc8e22d57d5dc8c048f15d8aed7dc4",
          "md5": "61a6104561744087fe62e7878948d9b7",
          "size": 12,
          "ingest_date": "2020-08-13",
          "tool_version": "tika-2.1.0",
          "media_type": "text/plain" 
        },
        {
          "filepath": "foo/bar.xml",
          "sha1": "2c789aee68c6803b0a45f1627a368a0af9785223",
          "md5": "5f859ade8cffd1a94543f4f660ab1b99",
          "size": 68,
          "ingest_date": "2020-03-16",
          "tool_version": "tika-2.1.0",
          "media_type": "text/xml"
        }
      ]
    }
  ]
}
